### ISSUE TITLE
Registering of devices is broken

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/push-notification-proxy#5]
```
2017/03/08 14:24:15 http: panic serving 127.0.0.1:59292: runtime error: invalid memory address or nil pointer dereference
goroutine 7 [running]:
net/http.(*conn).serve.func1(0xc420072900)
	/usr/local/go/src/net/http/server.go:1491 +0x12a
panic(0x7ef9a0, 0xc42000c110)
	/usr/local/go/src/runtime/panic.go:458 +0x243
database/sql.(*DB).conn(0x0, 0xc420051801, 0x579e75, 0xc420030018, 0x0)
	/usr/local/go/src/database/sql/sql.go:781 +0x3a
database/sql.(*DB).query(0x0, 0x87159b, 0x45, 0xc4200519f0, 0x1, 0x1, 0x1, 0x10, 0xc420156730, 0x0)
	/usr/local/go/src/database/sql/sql.go:1074 +0x3b
database/sql.(*DB).Query(0x0, 0x87159b, 0x45, 0xc4200519f0, 0x1, 0x1, 0x489a01, 0xc420156730, 0xc420051948)
	/usr/local/go/src/database/sql/sql.go:1062 +0x90
database/sql.(*DB).QueryRow(0x0, 0x87159b, 0x45, 0xc4200519f0, 0x1, 0x1, 0xc42000b000)
	/usr/local/go/src/database/sql/sql.go:1143 +0x70
main.savePushToken(0x0, 0xc42015c48a, 0x40, 0xc42001f920, 0x58, 0xc420136b40, 0x1c2, 0x0, 0x20)
	/home/nickv/Nextcloud/sdk-go/src/nextcloud/push-notification-proxy/device-handling.go:94 +0x1b3
main.deviceRequestHandling(0xa31600, 0xc42012a8f0, 0xc4200d02d0)
	/home/nickv/Nextcloud/sdk-go/src/nextcloud/push-notification-proxy/device-handling.go:57 +0x4a0
net/http.HandlerFunc.ServeHTTP(0x893c20, 0xa31600, 0xc42012a8f0, 0xc4200d02d0)
	/usr/local/go/src/net/http/server.go:1726 +0x44
net/http.(*ServeMux).ServeHTTP(0xc4201580c0, 0xa31600, 0xc42012a8f0, 0xc4200d02d0)
	/usr/local/go/src/net/http/server.go:2022 +0x7f
net/http.serverHandler.ServeHTTP(0xc420072780, 0xa31600, 0xc42012a8f0, 0xc4200d02d0)
	/usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc420072900, 0xa31c40, 0xc420012e00)
	/usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2293 +0x44d
```

https://github.com/nextcloud/push-notification-proxy/blob/master/device-handling.go#L94
I added a log, and `deviceIdentifier` is set to `bX+fVPw0rCUv8QHNjMqrPF1aqKv16UN5QC/oiC4aq7ChV0vDUcLvAwbmxYmNUYygsxEF6+ddnPpIDaoNlyMqDQ==`

Any idea @leonklingele

**Comment by nickvergessen** [comment]
I guess it's that somehow
https://github.com/nextcloud/push-notification-proxy/blob/master/main.go#L13
is not working anymore. It looks like if db has already no connection anymore

**Comment by nickvergessen** [comment]
Fixed via https://github.com/nextcloud/push-notification-proxy/commit/635556761e9df40dfc5c3c76de0157a95ec0bff6
